name: CI

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: Erlang/OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp:
          - '21.0'
          - '21.3'
          - '22.0'
          - '24.1'
        include:
          - otp: '21.0'
            rebar: '3.15.2'
          - otp: '21.3'
            rebar: '3.15.2'
          - otp: '22.0'
            rebar: '3.17.0'
          - otp: '24.1'
            rebar: '3.17.0'
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install libyaml-dev
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download Erlang/OTP ${{matrix.otp}} and Rebar ${{matrix.rebar}}
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar}}
      - name: Cache Rebar data
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3
          key: ${{runner.os}}-${{matrix.otp}}-${{hashFiles('rebar.config')}}
      - name: Download dependencies
        run: rebar3 get-deps
      - name: Compile code
        run: rebar3 compile
      - name: Analyze cross references
        run: rebar3 xref
      - name: Perform static code analysis
        run: rebar3 dialyzer
      - name: Run test suite
        run: rebar3 ct
